# Generated by Django 3.0.3 on 2020-03-12 01:12

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgupload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imgupload',
            name='img',
            field=models.ImageField(upload_to=post.models.generateName),
        ),
    ]
