# Generated by Django 3.0.3 on 2020-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200312_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
